 spring.application.name=Notes-app
 spring.datasource.url=jdbc:h2:file:./notedb
 spring.datasource.driverClassName=org.h2.Driver
 spring.datasource.username=VK
 spring.datasource.password=
 spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
 spring.jpa.hibernate.ddl-auto=update
 spring.h2.console.enabled=true
 spring.h2.console.path=/h2-console



